### ISSUE TITLE
ItemsAdder 

### ISSUE THREAD

**Issue by Tylwen** [OsipXD/MimicAPI#17]
[18:54:09 ERROR]: [Mimic] [ACF] Exception in command: mimic items info 
[18:54:09 ERROR]: [Mimic] [ACF] java.lang.reflect.InvocationTargetException
[18:54:09 ERROR]: [Mimic] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:54:09 ERROR]: [Mimic] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:54:09 ERROR]: [Mimic] [ACF]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:54:09 ERROR]: [Mimic] [ACF]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.shade.acf.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.shade.acf.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.shade.acf.commands.BaseCommand.execute(BaseCommand.java:513)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.shade.acf.commands.RootCommand.execute(RootCommand.java:99)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.shade.acf.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[18:54:09 ERROR]: [Mimic] [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:54:09 ERROR]: [Mimic] [ACF]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[18:54:09 ERROR]: [Mimic] [ACF]         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:54:09 ERROR]: [Mimic] [ACF]         at java.base/java.lang.Thread.run(Thread.java:834)
[18:54:09 ERROR]: [Mimic] [ACF] Caused by: java.lang.AbstractMethodError: Receiver class dev.lone.itemsadder.Core.OtherPlugins.b.a does not define or inherit an implementation of the resolved method 'java.util.Collection getKnownIds()' of interface ru.endlesscode.mimic.items.BukkitItemsRegistry.
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.impl.mimic.MimicItemsRegistry.getKnownIds(MimicItemsRegistry.kt:45)
[18:54:09 ERROR]: [Mimic] [ACF]         at ru.endlesscode.mimic.command.ItemsSubcommand.info(ItemsSubcommand.kt:43)
[18:54:09 ERROR]: [Mimic] [ACF]         ... 28 more

**Comment by Tylwen** [comment]
Mimic 0.5 et ItemsAdder 2.4.2
Server Paper-779, 1.16.5

Need add hook ItemsAdder

**Comment by LoneDev6** [comment]
They may have changed the API, I coded this compatibility on 2020-10-27.
Can anyone guide me into updating? 
Thanks.

**Comment by osipxd** [comment]
@LoneDev6, signature of `getItem` was slightly changed in version [0.6](https://github.com/EndlessCodeGroup/Mimic/releases/tag/v0.6). There was added optional parameter `Object payload`. Can you support it?

**Comment by LoneDev6** [comment]
Hello @osipxd , I removed Mimic support in 2.5.0, I'll re-add it right away in 2.5.3.
Thanks for you message.
