### ISSUE TITLE
MMOItems: `ClassNotFoundException: net.mmogroup.mmolib.api.item.NBTItem`

### ISSUE THREAD

**Issue by osipxd** [OsipXD/MimicAPI#24]
```java
Caused by: java.lang.ClassNotFoundException: net.mmogroup.mmolib.api.item.NBTItem
        at ru.endlesscode.mimic.impl.mmoitems.MmoItemsWrapper.getNbtItem(MmoItemsWrapper.kt:13) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mmoitems.MmoItemsRegistry.getItemId(MmoItemsRegistry.kt:48) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mmoitems.MmoItemsRegistry.getItemId(MmoItemsRegistry.kt:26) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mimic.SafeBukkitItemsRegistryKt.tryGetItemId(SafeBukkitItemsRegistry.kt:54) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mimic.MimicItemsRegistry$getItemId$1.invoke(MimicItemsRegistry.kt:66) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mimic.MimicItemsRegistry$getItemId$1.invoke(MimicItemsRegistry.kt:66) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.shade.kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.shade.kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.shade.kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.shade.kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mimic.MimicItemsRegistry.getItemId(MimicItemsRegistry.kt:67) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.mimic.impl.mimic.MimicItemsRegistry.getItemId(MimicItemsRegistry.kt:34) ~[mimic-bukkit-0.6.2-all.jar:?]
        at ru.endlesscode.inventory.slot.WildcardItemValidator.isValid(WildcardItemValidator.kt:59) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.slot.ContainerInventorySlot.canHold(ContainerInventorySlot.kt:179) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.slot.ContainerInventorySlot.placeItem(ContainerInventorySlot.kt:127) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.CustomInventory.placeItemInteraction(CustomInventory.kt:609) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.CustomInventory.handleSlotInteraction(CustomInventory.kt:561) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.CustomInventory.handleInteraction$core(CustomInventory.kt:547) ~[ECInventory-0.1.2.jar:?]
        at ru.endlesscode.inventory.internal.listener.InventoryClicksRouter.onClick(InventoryClicksRouter.kt:89) ~[ECInventory-0.1.2.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        ... 18 more
```

**Comment by osipxd** [comment]
Issue will be fixed in v0.6.3 but integrations should be moved into [MMOItems](https://git.lumine.io/mythiccraft/mmoitems) and [MMOCore](https://git.lumine.io/mythiccraft/mmocore) since it is open source.
